-- 1. Profiles Table to store user data linked to Supabase Auth
create table profiles (
  id uuid references auth.users on delete cascade not null primary key,
  updated_at timestamp with time zone,
  full_name text,
  avatar_url text,
  location text,
  is_friend boolean default false,
  kingdom_id_number text,
  authority_level integer default 1,
  tribe text,
  badge text,
  citizenship_status text default 'Active',
  authority_title text,
  consistency_score integer default 0,
  readiness_level text
);

-- RLS for profiles
alter table profiles enable row level security;
create policy "Public profiles are viewable by everyone." on profiles for select using (true);
create policy "Users can insert their own profile." on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile." on profiles for update using (auth.uid() = id);

-- Trigger to create a profile when a new user signs up
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 2. Announcements Table
create table announcements (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    title text not null,
    content text,
    category text,
    date date not null
);
-- RLS for announcements
alter table announcements enable row level security;
create policy "Announcements are viewable by everyone." on announcements for select using (true);
create policy "Admins can manage announcements." on announcements for all using (
  (select auth.uid() in (select id from profiles where authority_level >= 4)) -- Example: Admin level 4+
);

-- 3. Conferences Table
create table conferences (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    dates text,
    location text,
    image_url text,
    image_hint text
);
-- RLS for conferences (public read, admin write)
alter table conferences enable row level security;
create policy "Conferences are viewable by everyone." on conferences for select using (true);
create policy "Admins can manage conferences." on conferences for all using (
  (select auth.uid() in (select id from profiles where authority_level >= 4))
);

-- 4. Courses Table
create table courses (
    id bigint generated by default as identity primary key,
    title text not null,
    description text,
    category text,
    image_url text,
    image_hint text
);
-- RLS for courses (public read, admin write)
alter table courses enable row level security;
create policy "Courses are viewable by everyone." on courses for select using (true);
create policy "Admins can manage courses." on courses for all using (
  (select auth.uid() in (select id from profiles where authority_level >= 4))
);

-- 5. Departments Table
create table departments (
    id bigint generated by default as identity primary key,
    name text not null unique,
    description text,
    icon text
);
-- RLS for departments (public read, admin write)
alter table departments enable row level security;
create policy "Departments are viewable by everyone." on departments for select using (true);
create policy "Admins can manage departments." on departments for all using (
  (select auth.uid() in (select id from profiles where authority_level >= 4))
);

-- 6. News Feed Table
create table news_feed (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    user_id uuid references public.profiles,
    title text,
    content text not null,
    image_url text,
    image_hint text
);
-- RLS for news (public read, admin/owner write)
alter table news_feed enable row level security;
create policy "News is viewable by everyone." on news_feed for select using (true);
create policy "Users can post news." on news_feed for insert with check (auth.uid() = user_id);
create policy "Admins or owners can delete news." on news_feed for delete using (
  auth.uid() = user_id or 
  (select auth.uid() in (select id from profiles where authority_level >= 4))
);

-- 7. Prayer Requests Table
create table prayer_requests (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default now(),
    user_id uuid references public.profiles, -- can be null for anonymous
    user_name text, -- for anonymous posts
    request text not null
);
-- RLS for prayer requests (public read, auth write)
alter table prayer_requests enable row level security;
create policy "Prayer requests are viewable by everyone." on prayer_requests for select using (true);
create policy "Authenticated users can submit prayer requests." on prayer_requests for insert with check (auth.role() = 'authenticated');
