-- This script creates the remaining content-focused tables for the application.

-- 1. Devotionals Table
CREATE TABLE IF NOT EXISTS devotionals (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    title TEXT NOT NULL,
    author TEXT,
    publish_date DATE NOT NULL,
    category TEXT,
    image_url TEXT,
    image_hint TEXT,
    content_text TEXT,
    audio_url TEXT,
    video_url TEXT
);
ALTER TABLE devotionals ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Devotionals are public." ON devotionals FOR SELECT USING (true);
CREATE POLICY "Admins can manage devotionals." ON devotionals FOR ALL USING ((SELECT auth.uid() IN (SELECT id FROM profiles WHERE authority_level >= 4)));

-- 2. Live Sessions / Replays Table
CREATE TABLE IF NOT EXISTS live_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    title TEXT NOT NULL,
    speaker TEXT,
    is_live BOOLEAN DEFAULT FALSE,
    video_url TEXT,
    image_url TEXT,
    image_hint TEXT
);
ALTER TABLE live_sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Live sessions are public." ON live_sessions FOR SELECT USING (true);
CREATE POLICY "Admins can manage live sessions." ON live_sessions FOR ALL USING ((SELECT auth.uid() IN (SELECT id FROM profiles WHERE authority_level >= 4)));

-- 3. Ministries Table
CREATE TABLE IF NOT EXISTS ministries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    description TEXT,
    logo_url TEXT,
    logo_hint TEXT
);
ALTER TABLE ministries ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Ministries are public." ON ministries FOR SELECT USING (true);
CREATE POLICY "Admins can manage ministries." ON ministries FOR ALL USING ((SELECT auth.uid() IN (SELECT id FROM profiles WHERE authority_level >= 4)));

-- 4. Empowerment Meetings Table
CREATE TABLE IF NOT EXISTS empowerment_meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    frequency TEXT,
    time TEXT,
    type TEXT,
    image_url TEXT,
    image_hint TEXT
);
ALTER TABLE empowerment_meetings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Empowerment meetings are public." ON empowerment_meetings FOR SELECT USING (true);
CREATE POLICY "Admins can manage empowerment meetings." ON empowerment_meetings FOR ALL USING ((SELECT auth.uid() IN (SELECT id FROM profiles WHERE authority_level >= 4)));

-- 5. Bible Stories Table
CREATE TABLE IF NOT EXISTS bible_stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug TEXT UNIQUE NOT NULL,
    category TEXT,
    title TEXT NOT NULL,
    image_url TEXT,
    image_hint TEXT,
    scripture TEXT,
    narrative TEXT[],
    revelation_title TEXT,
    revelation_text TEXT,
    life_application TEXT[],
    declaration TEXT
);
ALTER TABLE bible_stories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Bible stories are public." ON bible_stories FOR SELECT USING (true);
CREATE POLICY "Admins can manage bible stories." ON bible_stories FOR ALL USING ((SELECT auth.uid() IN (SELECT id FROM profiles WHERE authority_level >= 4)));

-- 6. Creative Activities Table
CREATE TABLE IF NOT EXISTS creative_activities (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    type TEXT,
    image_url TEXT,
    image_hint TEXT,
    file_url TEXT
);
ALTER TABLE creative_activities ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Creative activities are public." ON creative_activities FOR SELECT USING (true);
CREATE POLICY "Admins can manage creative activities." ON creative_activities FOR ALL USING ((SELECT auth.uid() IN (SELECT id FROM profiles WHERE authority_level >= 4)));

-- 7. Memory Verse Songs Table
CREATE TABLE IF NOT EXISTS memory_verse_songs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    scripture TEXT,
    audio_url TEXT,
    image_url TEXT,
    image_hint TEXT
);
ALTER TABLE memory_verse_songs ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Memory verse songs are public." ON memory_verse_songs FOR SELECT USING (true);
CREATE POLICY "Admins can manage memory verse songs." ON memory_verse_songs FOR ALL USING ((SELECT auth.uid() IN (SELECT id FROM profiles WHERE authority_level >= 4)));
