-- This script adds the remaining tables for the Faith Connect Global application.
-- Run this script AFTER the 0001_initial_schema.sql script.

-- 8. Life Groups Table
CREATE TABLE IF NOT EXISTS life_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    name TEXT NOT NULL,
    description TEXT,
    category TEXT,
    leader_id UUID REFERENCES public.profiles(id),
    image_url TEXT,
    image_hint TEXT,
    members INT DEFAULT 1
);
ALTER TABLE life_groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Life groups are viewable by everyone." ON life_groups FOR SELECT USING (true);
CREATE POLICY "Admins can manage life groups." ON life_groups FOR ALL USING (
  (SELECT authority_level FROM profiles WHERE id = auth.uid()) >= 4
);

-- 9. Meetings Table
CREATE TABLE IF NOT EXISTS meetings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    title TEXT NOT NULL,
    description TEXT,
    date TIMESTAMP WITH TIME ZONE,
    department TEXT
);
ALTER TABLE meetings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Meetings are viewable by everyone." ON meetings FOR SELECT USING (true);
CREATE POLICY "Admins can manage meetings." ON meetings FOR ALL USING (
  (SELECT authority_level FROM profiles WHERE id = auth.uid()) >= 4
);

-- 10. Annual Calendar Table
CREATE TABLE IF NOT EXISTS annual_calendar (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month TEXT NOT NULL UNIQUE,
    theme TEXT,
    purpose TEXT,
    activities TEXT[]
);
ALTER TABLE annual_calendar ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Calendar is viewable by everyone." ON annual_calendar FOR SELECT USING (true);
CREATE POLICY "Admins can manage calendar." ON annual_calendar FOR ALL USING (
  (SELECT authority_level FROM profiles WHERE id = auth.uid()) >= 4
);

-- 11. Discipleship Relationships Table
CREATE TABLE IF NOT EXISTS discipleship_relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    disciple_id UUID REFERENCES public.profiles(id) NOT NULL,
    discipler_id UUID REFERENCES public.profiles(id) NOT NULL
);
ALTER TABLE discipleship_relationships ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own discipleship relationships." ON discipleship_relationships FOR SELECT USING (auth.uid() = disciple_id OR auth.uid() = discipler_id);
CREATE POLICY "Admins can manage discipleship." ON discipleship_relationships FOR ALL USING (
  (SELECT authority_level FROM profiles WHERE id = auth.uid()) >= 4
);

-- 12. Teachings Table
CREATE TABLE IF NOT EXISTS teachings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    department TEXT,
    file_url TEXT,
    file_name TEXT
);
ALTER TABLE teachings ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Teachings are viewable by authenticated users." ON teachings FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Admins can manage teachings." ON teachings FOR ALL USING (
  (SELECT authority_level FROM profiles WHERE id = auth.uid()) >= 4
);

-- 13. Visitors Program Table
CREATE TABLE IF NOT EXISTS visitors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) NOT NULL,
    track TEXT,
    progress INT DEFAULT 0,
    mentor_id UUID REFERENCES public.profiles(id),
    status TEXT,
    war_room_access BOOLEAN DEFAULT false,
    court_access BOOLEAN DEFAULT false
);
ALTER TABLE visitors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view their own visitor status." ON visitors FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Admins can manage visitors." ON visitors FOR ALL USING (
  (SELECT authority_level FROM profiles WHERE id = auth.uid()) >= 4
);

-- 14. Stories Table
CREATE TABLE IF NOT EXISTS stories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) NOT NULL,
    media_url TEXT NOT NULL,
    media_type TEXT, -- 'image' or 'video'
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
ALTER TABLE stories ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can view stories." ON stories FOR SELECT USING (auth.role() = 'authenticated');
CREATE POLICY "Users can create their own stories." ON stories FOR INSERT WITH CHECK (auth.uid() = user_id);
CREATE POLICY "Users can delete their own stories." ON stories FOR DELETE USING (auth.uid() = user_id);

-- 15. Friend Requests Table
CREATE TABLE IF NOT EXISTS friend_requests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requester_id UUID REFERENCES public.profiles(id) NOT NULL,
    receiver_id UUID REFERENCES public.profiles(id) NOT NULL,
    status TEXT DEFAULT 'pending' -- 'pending', 'accepted', 'declined'
);
ALTER TABLE friend_requests ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Users can manage their own friend requests." ON friend_requests FOR ALL USING (auth.uid() = requester_id OR auth.uid() = receiver_id);

-- 16. Family Groups Table
CREATE TABLE IF NOT EXISTS family_groups (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    father_id UUID REFERENCES public.profiles(id),
    mother_id UUID REFERENCES public.profiles(id),
    monthly_focus TEXT,
    unity_score TEXT
);
ALTER TABLE family_groups ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Family group data is private." ON family_groups FOR ALL USING (
    auth.uid() = father_id OR auth.uid() = mother_id
);
CREATE POLICY "Admins can manage family groups." ON family_groups FOR ALL USING (
  (SELECT authority_level FROM profiles WHERE id = auth.uid()) >= 4
);

-- 17. Service Elements Table
CREATE TABLE IF NOT EXISTS service_elements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    description TEXT,
    details TEXT
);
ALTER TABLE service_elements ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Service elements are public." ON service_elements FOR SELECT USING (true);
CREATE POLICY "Admins can manage service elements." ON service_elements FOR ALL USING (
  (SELECT authority_level FROM profiles WHERE id = auth.uid()) >= 4
);
